### ISSUE TITLE
Copyright license violation

### ISSUE THREAD

**Issue by swiftsearch** [githubrobbi/Ultra-Fast-File-Search#2]
I just wanted to bring to your attention that this repository violates the license of the [original project](https://sourceforge.net/projects/swiftsearch/) from which you copied it.

Not only had you previously specifically agreed not to distribute the source code, but the source code is **not** MIT licensed as you have misrepresented in the repository, either.

These violate the terms of the agreement in the project. Please take down the repository and respect the terms of the agreement.

**Comment by githubrobbi** [comment]
Subject: License Compliance Update and Documentation Revision

Dear swiftsearch,

I hope this message finds you well. I am writing to inform you that I have recently addressed and rectified the licensing and documentation issues associated with the adapted work based on your original project. Please be advised that the adapted work is now licensed under the same Creative Commons Attribution Non-Commercial License 2.0 (https://creativecommons.org/licenses/by-nc/2.0/legalcode), in compliance with your initial licensing terms.

As per the provisions of the Creative Commons Attribution Non-Commercial License V2.0, I understand that I am permitted to share (copy and redistribute the material in any medium or format) and adapt (remix, transform, and build upon the material) the work in question, as long as it is done in accordance with the license terms.

I trust that these modifications adequately address the licensing concerns and ensure that the repository is now in full compliance with the original licensing requirements.

Please feel free to contact me if you have any further questions or concerns.

Sincerely,

Robert

**Comment by githubrobbi** [comment]
Hi,

I appreciate your detailed feedback and guidance. In response to your concerns, I have taken the following actions:

- Created a new branch containing only one commit, which includes all the corrected files with the appropriate license.  Deleted all other branches to ensures that the old branch, tree, and commits are no longer accessible.

- Updated the advertisement to clarify the non-commercial use of the tool. This should prevent any confusion about the licensing and intended usage.

Thank you for bringing these issues to my attention and for providing valuable suggestions on how to address them. Your input has been instrumental in improving the project.

Best regards,

Robert

**Comment by githubrobbi** [comment]
You're welcome! I understand the concern regarding the confusion that the phrase "Professional IT Admin Tool" may cause. Here's an alternative suggestion based on your input:

"Ultra Fast File Search for Windows: Command-line tool for lightning-fast searches (non-commercial use only)"

This revised description should help clarify that the tool is intended for non-commercial use while still highlighting its primary function and platform.
