### ISSUE TITLE
Is compiled uffs.com broken?

### ISSUE THREAD

**Issue by bowanner** [githubrobbi/Ultra-Fast-File-Search#8]
Downloaded the compiledf uffs.com from this page. I can run uffs.com --help and a little more. BUT then it refuses to use any search string in whatever format:

uffs.com --columns=path,size,created  'C:\Prog**'
MMMmmm that was FAST ... maybe your searchstring was wrong?     'C:\Prog**'
Search path. E.g. 'C:/' or 'C:\Prog**'
Finished        in 0 s

uffs.com --columns=path,size,created  'C:/'
MMMmmm that was FAST ... maybe your searchstring was wrong?     'C:\'
Search path. E.g. 'C:/' or 'C:\Prog**'
Finished        in 0 s

uffs.com --columns=path,size,created  'C:\'
MMMmmm that was FAST ... maybe your searchstring was wrong?     'C:\'
Search path. E.g. 'C:/' or 'C:\Prog**'
Finished        in 0 s

uffs.com --columns=path,size,created  --drives='C:, D:'
Drives?         1       D:
MMMmmm that was FAST ... maybe your searchstring was wrong?     D:'
Search path. E.g. 'C:/' or 'C:\Prog**'
Finished        in 1 s

Best regards
Bo W

**Comment by manuel76413** [comment]
maybe you should use administrative privilege

**Comment by bowanner** [comment]
Everything above was run as Administrator in a CMD window i Windows 11. Maybe you should TEST it yourself?
